wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      4: 3.8.6
      5: 0.10.27
      6: 4.2.2
      8:
      - 5
